// SPDX-License-Identifier: GPL-3.0-only
// Copyright © 2026 infraBuilder SASU and contributors

package taxonomy_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tobby-fetch/tobby-fetch/internal/taxonomy"
)

// Generation markers. The published pages carry the rendered table
// between them, verbatim; nothing else in either page is generated.
const (
	exitTableStart = "<!-- generated:exit-codes -->"
	exitTableEnd   = "<!-- /generated:exit-codes -->"
)

// publishedExitTables maps each page that carries the table to the
// language it carries it in. English lives on the CLI reference, which is
// also the page the binary embeds for offline reading; French lives on the
// error reference, the only French reference page there is until the
// documentation's own milestone (website/README-docs.md).
var publishedExitTables = map[string]string{
	"website/src/content/docs/docs/reference/cli.md":       "en",
	"website/src/content/docs/fr/docs/reference/errors.md": "fr",
}

// TestExitCodeTableIsExhaustive is the R-08 promise stated as a test: the
// published table is the set of exit codes the product can return, in
// both directions — no code outside the table, no row without a producer.
//
// The CLI-side half (each row produced through the mapping the process
// performs) lives in internal/cli; this half owns what the taxonomy
// itself can produce.
func TestExitCodeTableIsExhaustive(t *testing.T) {
	seenCode := map[int]string{}
	seenName := map[string]bool{}
	for _, e := range taxonomy.ExitCodes() {
		if other, clash := seenCode[e.Code]; clash {
			t.Errorf("exit code %d is published twice, as %q and %q", e.Code, other, e.Name)
		}
		seenCode[e.Code] = e.Name
		if seenName[e.Name] {
			t.Errorf("exit-code name %q is published twice", e.Name)
		}
		seenName[e.Name] = true
		if name, ok := taxonomy.ExitCodeName(e.Code); !ok || name != e.Name {
			t.Errorf("ExitCodeName(%d) = %q, %v; want %q", e.Code, name, ok, e.Name)
		}
		for _, lang := range taxonomy.Languages() {
			title, meaning := taxonomy.ExitCodeMessage(lang, e)
			if title == e.Name || meaning == e.Name {
				t.Errorf("exit code %d (%s) has no %s message: the catalog fell back to the machine name",
					e.Code, e.Name, lang)
			}
		}
	}

	// Every class of the taxonomy, and every catalog entry, exits on a
	// published row. A class that did not would be a number an operator
	// can observe and cannot look up.
	for _, class := range taxonomy.Classes() {
		if _, ok := seenCode[class.ExitCode()]; !ok {
			t.Errorf("a class exits %d, which the published table does not list", class.ExitCode())
		}
	}
	for _, entry := range taxonomy.All() {
		if _, ok := seenCode[entry.Class.ExitCode()]; !ok {
			t.Errorf("%s exits %d, which the published table does not list", entry.Code, entry.Class.ExitCode())
		}
	}
	// The two codes no class produces are the ones the process reserves
	// by convention. Naming them here is what makes "exhaustive" mean
	// something: the table must carry them even though no catalog walk
	// reaches them.
	for code, what := range map[int]string{
		taxonomy.ExitOK:             "success",
		taxonomy.ExitUsage:          "usage errors",
		taxonomy.ExitChangesPlanned: "the plan-mode outcome of FR-055 (R-04)",
	} {
		if _, ok := seenCode[code]; !ok {
			t.Errorf("exit code %d (%s) is returned by the CLI but is not in the published table", code, what)
		}
	}
}

// TestPublishedExitCodeTableMatchesTheCode is the drift guard. R-08 puts
// the table under the semantic-versioning promise, and a promise about a
// number no reader can check against the code is not one: the reference
// pages carry the table generated by ExitCodeTable, verbatim, and this
// test fails the build the moment the two disagree.
func TestPublishedExitCodeTableMatchesTheCode(t *testing.T) {
	root := repoRoot(t)
	for page, lang := range publishedExitTables {
		//nolint:gosec // G304: page comes from the fixed map above, not from input
		raw, err := os.ReadFile(filepath.Join(root, page))
		if err != nil {
			t.Fatalf("reading %s: %v", page, err)
		}
		// The rendered table is built with "\n", so the page is normalized
		// rather than trusting a checkout to have kept it that way (NFR-018).
		text := strings.ReplaceAll(string(raw), "\r\n", "\n")
		start := strings.Index(text, exitTableStart)
		end := strings.Index(text, exitTableEnd)
		if start < 0 || end < 0 || end < start {
			t.Errorf("%s carries no generated exit-code table: wrap it in %s … %s",
				page, exitTableStart, exitTableEnd)
			continue
		}
		got := strings.TrimSpace(text[start+len(exitTableStart) : end])
		want := strings.TrimSpace(taxonomy.ExitCodeTable(lang))
		if got != want {
			t.Errorf("%s: the published exit-code table has drifted from the code (%s).\n"+
				"Replace the block between the markers with:\n\n%s\n", page, lang, want)
		}
	}
}
