#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Copyright © 2026 infraBuilder SASU and contributors
#
# Milestone-3 crucible scenario (ADR-0014, DEVELOPMENT-PLAN §2.3): the
# recipe engine on real nodes, with REAL cosign signatures — the crucible
# owns the live compatibility proof of the key-based verification path
# (FR-033, RECIPE-SPEC §12).
#
#   1. Fixtures: an upstream registry node hosts a multi-arch image, a
#      FileSet, and a cookbook holding a cooked recipe signed with a key
#      generated by this scenario (cosign key-based, ADR-0007).
#   2. A secure Tobby node synchronizes a Retriever: signature verified,
#      ingredients fetched by pinned digest under their relocated paths
#      (FR-035), platform selection sparse (FR-022), recipe + signature
#      copied into the local store.
#   3. Tampering: a recipe version signed by a FOREIGN key is refused with
#      TBY-SIG-001, per item — the sound recipe still synchronizes.
#   4. Idempotence (NFR-009): a second synchronization transfers zero
#      bytes.
#   5. FileSet HTTP serving (FR-047): the verified FileSet is served under
#      /files/ with byte-range support; anonymous access works only
#      because the scenario opts this FileSet in.
#   6. Cascade (FR-036): a second Tobby node consumes the FIRST node's
#      store through source substitution, with the recipe UNMODIFIED; the
#      relocated paths are identical on both nodes.
#
# Topology: tbc-m3-source (container, tbc-net) plays the upstream
# registry+cookbook; tbc-m3-node and tbc-m3-downstream (containers,
# tbc-net) run the secure Tobby instances under test.
set -eu

DIR="$(cd "$(dirname "$0")" && pwd)"
. "$DIR/../../lib.sh"

IMAGE="${CRUCIBLE_IMAGE:-images:alpine/3.22}"
ARCH="$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/')"
CRED_USER="admin"
CRED_PASS="m3-crucible-pass"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

report_start

# -- Tooling: the real cosign signs the fixtures ------------------------------
COSIGN="${COSIGN:-cosign}"
if ! command -v "$COSIGN" >/dev/null 2>&1; then
    GOBIN="$WORK/bin" go install github.com/sigstore/cosign/v3/cmd/cosign@v3.0.4 ||
        fail "cosign unavailable and go install failed"
    COSIGN="$WORK/bin/cosign"
fi
check "cosign available ($($COSIGN version 2>/dev/null | head -1 || echo unknown))"

# -- Build the binary under test ---------------------------------------------
( cd "$DIR/../../.." && GOOS=linux GOARCH="$ARCH" CGO_ENABLED=0 \
    go build -trimpath -o /tmp/tobby-crucible ./cmd/tobby )
check "built tobby for linux/$ARCH"

for inst in tbc-m3-source tbc-m3-node tbc-m3-downstream; do
    inc delete --force "$inst" 2>/dev/null || true
    inc launch "$IMAGE" "$inst" --profile tbc-connected-node
    inc file push /tmp/tobby-crucible "$inst/usr/bin/tobby"
    inc exec "$inst" -- chmod +x /usr/bin/tobby
done
check "instances launched (source + node + downstream)"

# The upstream registry is a Tobby with the explicit FR-075 opt-out — a
# standards-compliant OCI registry (m1 proves its wire behavior).
inc exec tbc-m3-source -- sh -c '
    nohup env TOBBY_MODE=passthrough TOBBY_STORAGE_ROOT=/srv/source \
        TOBBY_AUTH_DISABLED=true \
        TOBBY_SERVER_ADDR=:8080 tobby serve >/var/log/tobby.log 2>&1 &
'
# A freshly launched instance has no address until DHCP completes, and
# this scenario reads all three at once: wait for each rather than
# capturing an empty string that only fails minutes later.
instance_ip() {
    i=0
    while :; do
        ip=$(inc list "$1" -c 4 -f csv | awk '{print $1}' | head -1)
        if [ -n "$ip" ]; then
            printf '%s' "$ip"
            return 0
        fi
        i=$((i + 1))
        [ "$i" -gt 60 ] && fail "instance $1 never received an address"
        sleep 1
    done
}
SOURCE_IP=$(instance_ip tbc-m3-source)
NODE_IP=$(instance_ip tbc-m3-node)
DOWN_IP=$(instance_ip tbc-m3-downstream)
wait_ready tbc-m3-source http://127.0.0.1:8080/readyz
check "upstream registry serving ($SOURCE_IP:8080)"

# -- 1. Fixtures: ingredients, keys, cooked signed recipe ---------------------
IMG_DIGEST=$( cd "$DIR/../../.." && go run ./test/topology/seed push "$SOURCE_IP:8080/library/sample:2.0.0" ) ||
    fail "seeding the sample image"
mkdir -p "$WORK/site"
printf 'crucible m3 fileset payload\n' > "$WORK/site/hello.txt"
printf 'second file for range requests: 0123456789abcdef\n' > "$WORK/site/range.txt"
FS_DIGEST=$( cd "$DIR/../../.." && go run ./test/topology/seed push-fileset "$SOURCE_IP:8080/filesets/site:1.0.0" "$WORK/site" ) ||
    fail "seeding the fileset"

( cd "$WORK" && COSIGN_PASSWORD= "$COSIGN" generate-key-pair >/dev/null 2>&1 )
( cd "$WORK" && COSIGN_PASSWORD= "$COSIGN" generate-key-pair --output-key-prefix foreign >/dev/null 2>&1 )
check "fixtures seeded (image $IMG_DIGEST, fileset $FS_DIGEST), key pairs generated"

cat > "$WORK/sample-app.yaml" <<EOF
apiVersion: recipe.tobby.dev/v1alpha1
kind: Recipe
metadata:
  name: sample-app
  version: 2.0.0
spec:
  ingredients:
    - name: sample
      kind: ContainerImage
      ref: $SOURCE_IP:8080/library/sample
      version: 2.0.0
      digest: $IMG_DIGEST
      platforms: [linux/amd64, linux/arm64]
    - name: site
      kind: FileSet
      ref: $SOURCE_IP:8080/filesets/site
      version: 1.0.0
      digest: $FS_DIGEST
EOF
RECIPE_DIGEST=$( cd "$DIR/../../.." && go run ./test/topology/seed push-recipe \
    "$SOURCE_IP:8080/cookbook/sample-app:2.0.0" "$WORK/sample-app.yaml" ) ||
    fail "publishing the cooked recipe"
# cosign 3.x defaults to the new bundle format, which attaches signatures
# through the Referrers API under a "sha256-<hex>" tag. RECIPE-SPEC §12.2
# and ADR-0007 pin the classic attached-signature convention
# ("sha256-<hex>.sig"), so the fixtures are signed in that format —
# --use-signing-config=false is what lets --tlog-upload=false through.
sign_recipe() {
    COSIGN_PASSWORD= "$COSIGN" sign --key "$1" --yes --allow-insecure-registry \
        --use-signing-config=false --new-bundle-format=false --tlog-upload=false "$2"
}
sign_recipe "$WORK/cosign.key" "$SOURCE_IP:8080/cookbook/sample-app@$RECIPE_DIGEST" >/dev/null 2>&1 ||
    fail "cosign signing the recipe"

# A second version signed by a FOREIGN key: the tamper case.
sed 's/version: 2.0.0/version: 2.0.1/' "$WORK/sample-app.yaml" > "$WORK/sample-app-2.0.1.yaml"
BAD_DIGEST=$( cd "$DIR/../../.." && go run ./test/topology/seed push-recipe \
    "$SOURCE_IP:8080/cookbook/sample-app:2.0.1" "$WORK/sample-app-2.0.1.yaml" ) ||
    fail "publishing the foreign-signed recipe"
sign_recipe "$WORK/foreign.key" "$SOURCE_IP:8080/cookbook/sample-app@$BAD_DIGEST" >/dev/null 2>&1 ||
    fail "cosign signing with the foreign key"
check "cooked recipe signed (trusted 2.0.0, foreign-signed 2.0.1)"

# -- 2. Secure node: configuration, account, synchronization ------------------
# The inline trust root is a YAML block scalar: its content must be
# indented MORE than the "key:" that introduces it (6 spaces), hence 8.
PUB_KEY_INDENTED=$(sed 's/^/        /' "$WORK/cosign.pub")
cat > "$WORK/node.yaml" <<EOF
mode: mirror
storage:
  root: /srv/store
state:
  root: /srv/state
server:
  addr: :8080
registries:
  insecure: ["$SOURCE_IP:8080"]
retriever:
  source: /etc/tobby/retriever.yaml
trust:
  roots:
    - name: crucible
      key: |
$PUB_KEY_INDENTED
files:
  filesets:
    - name: site
      ref: $SOURCE_IP:8080/filesets/site
      anonymous: true
EOF
cat > "$WORK/retriever.yaml" <<EOF
apiVersion: recipe.tobby.dev/v1alpha1
kind: Retriever
metadata:
  name: crucible-zone
spec:
  cookbook: $SOURCE_IP:8080/cookbook
  recipes:
    - name: sample-app
      version: "2.0.0"
EOF
inc exec tbc-m3-node -- mkdir -p /etc/tobby
inc file push "$WORK/node.yaml" tbc-m3-node/etc/tobby/config.yaml
inc file push "$WORK/retriever.yaml" tbc-m3-node/etc/tobby/retriever.yaml
inc exec tbc-m3-node -- sh -c "printf '%s\n' '$CRED_PASS' |
    tobby user add $CRED_USER --state-root /srv/state --password-stdin" >/dev/null ||
    fail "creating the node account"
inc exec tbc-m3-node -- sh -c '
    nohup tobby serve --config /etc/tobby/config.yaml >>/var/log/tobby.log 2>&1 &
'
wait_ready tbc-m3-node http://127.0.0.1:8080/readyz
check "secure node configured (trust root, retriever, fileset) and serving"

API="http://$NODE_IP:8080/api/v1"
CRED="$CRED_USER:$CRED_PASS"

sync_and_wait() {
    api="$1"; cred="$2"
    tid=$(curl -fsS -u "$cred" -X POST "$api/sync" | jq -r '.task.id') || return 1
    i=0
    while :; do
        status=$(curl -fsS -u "$cred" "$api/tasks/$tid" | jq -r '.task.status')
        [ "$status" = "done" ] || [ "$status" = "failed" ] && break
        i=$((i + 1)); [ "$i" -gt 300 ] && return 1
        sleep 0.4
    done
    printf '%s' "$tid"
}

TASK_ID=$(sync_and_wait "$API" "$CRED") || fail "synchronization never settled"
STATUS=$(curl -fsS -u "$CRED" "$API/tasks/$TASK_ID" | jq -r '.task.status')
[ "$STATUS" = "done" ] || fail "synchronization ended $STATUS, want done"

RELOCATED="${SOURCE_IP}_8080/library/sample"
STORED=$(curl -fsS -u "$CRED" "$API/content/$RELOCATED/-/tags/2.0.0" | jq -r '.digest')
[ "$STORED" = "$IMG_DIGEST" ] || fail "stored digest $STORED differs from pinned $IMG_DIGEST"
PRESENT=$(curl -fsS -u "$CRED" "$API/content/$RELOCATED/-/tags/2.0.0" |
    jq '[.platforms[] | select(.present)] | length')
[ "$PRESENT" = "2" ] || fail "present platforms $PRESENT, want the 2 selected (sparse index)"
COOKBOOK_REPO="${SOURCE_IP}_8080/cookbook/sample-app"
SIG_TAG="$(printf '%s' "$RECIPE_DIGEST" | sed 's/sha256:/sha256-/').sig"
curl -fsS -u "$CRED" "$API/content/$COOKBOOK_REPO/-/tags/2.0.0" >/dev/null ||
    fail "recipe artifact missing from the local cookbook path"
curl -fsS -u "$CRED" "$API/content/$COOKBOOK_REPO/-/tags/$SIG_TAG" >/dev/null ||
    fail "recipe signature artifact not copied (§12.2)"
check "signed recipe synchronized: pinned digests intact, sparse index (2/3), signature copied"

# -- 3. Tampering: foreign-signed recipe refused per item ---------------------
sed 's/version: "2.0.0"/version: "2.0.1"/' "$WORK/retriever.yaml" > "$WORK/retriever-bad.yaml"
inc file push "$WORK/retriever-bad.yaml" tbc-m3-node/etc/tobby/retriever.yaml
BAD_TASK=$(sync_and_wait "$API" "$CRED") || fail "tamper synchronization never settled"
BAD_CODE=$(curl -fsS -u "$CRED" "$API/tasks/$BAD_TASK" |
    jq -r '[.task.items[] | select(.error != null) | .error.code] | first')
[ "$BAD_CODE" = "TBY-SIG-001" ] || fail "foreign-signed recipe yielded $BAD_CODE, want TBY-SIG-001"
if curl -fsS -u "$CRED" "$API/content/$COOKBOOK_REPO/-/tags/2.0.1" >/dev/null 2>&1; then
    fail "foreign-signed recipe landed in the store"
fi
inc file push "$WORK/retriever.yaml" tbc-m3-node/etc/tobby/retriever.yaml
check "foreign-signed recipe refused (TBY-SIG-001), nothing landed"

# -- 4. Idempotence: second run transfers zero bytes --------------------------
TASK2=$(sync_and_wait "$API" "$CRED") || fail "second synchronization never settled"
MOVED=$(curl -fsS -u "$CRED" "$API/tasks/$TASK2" |
    jq '[.task.items[].size_bytes // 0] | add // 0')
[ "$MOVED" = "0" ] || fail "second run moved $MOVED bytes, want 0 (NFR-009)"
check "idempotence: second synchronization transferred zero bytes"

# -- 4b. The other published signature layout is accepted too -----------------
# cosign 3.x publishes a Sigstore bundle REFERRING to the subject instead of
# the classic attached tag. RECIPE-SPEC §12.2 requires consumers to accept
# both, because the choice belongs to whoever signs — this step signs with
# cosign's own defaults (minus the transparency log, unreachable here) and
# expects the same verdict as the classic layout.
sed 's/version: 2.0.0/version: 2.0.2/' "$WORK/sample-app.yaml" > "$WORK/sample-app-2.0.2.yaml"
BUNDLE_DIGEST=$( cd "$DIR/../../.." && go run ./test/topology/seed push-recipe \
    "$SOURCE_IP:8080/cookbook/sample-app:2.0.2" "$WORK/sample-app-2.0.2.yaml" ) ||
    fail "publishing the bundle-signed recipe"
COSIGN_PASSWORD= "$COSIGN" sign --key "$WORK/cosign.key" --yes --allow-insecure-registry \
    --use-signing-config=false --tlog-upload=false \
    "$SOURCE_IP:8080/cookbook/sample-app@$BUNDLE_DIGEST" >/dev/null 2>&1 ||
    fail "cosign signing in the bundle layout"

sed 's/version: "2.0.0"/version: "2.0.2"/' "$WORK/retriever.yaml" > "$WORK/retriever-bundle.yaml"
inc file push "$WORK/retriever-bundle.yaml" tbc-m3-node/etc/tobby/retriever.yaml
BUNDLE_TASK=$(sync_and_wait "$API" "$CRED") || fail "bundle-layout synchronization never settled"
BSTATUS=$(curl -fsS -u "$CRED" "$API/tasks/$BUNDLE_TASK" | jq -r '.task.status')
[ "$BSTATUS" = "done" ] || fail "bundle-layout synchronization ended $BSTATUS, want done"
curl -fsS -u "$CRED" "$API/content/$COOKBOOK_REPO/-/tags/2.0.2" >/dev/null ||
    fail "bundle-signed recipe did not land"
inc file push "$WORK/retriever.yaml" tbc-m3-node/etc/tobby/retriever.yaml
check "the Sigstore bundle layout (cosign 3.x default) verifies like the classic one"

# -- 5. FileSet served over /files/ with ranges (FR-047) ----------------------
BODY=$(curl -fsS "http://$NODE_IP:8080/files/site/hello.txt") ||
    fail "anonymous fileset read failed"
[ "$BODY" = "crucible m3 fileset payload" ] || fail "fileset content mismatch"
RANGE_CODE=$(curl -s -o "$WORK/range.out" -w '%{http_code}' -r 0-5 \
    "http://$NODE_IP:8080/files/site/range.txt")
[ "$RANGE_CODE" = "206" ] || fail "range request answered $RANGE_CODE, want 206"
[ "$(cat "$WORK/range.out")" = "second" ] || fail "range bytes mismatch"
TRAV_CODE=$(curl -s -o /dev/null -w '%{http_code}' \
    "http://$NODE_IP:8080/files/site/..%2f..%2fetc%2fpasswd")
[ "$TRAV_CODE" = "400" ] || [ "$TRAV_CODE" = "404" ] ||
    fail "path traversal answered $TRAV_CODE"
check "FileSet served anonymously (opt-in), 206 on ranges, traversal refused"

# -- 6. Cascade: downstream node, recipes unmodified, identical paths ---------
cat > "$WORK/down.yaml" <<EOF
mode: mirror
storage:
  root: /srv/store
state:
  root: /srv/state
server:
  addr: :8080
registries:
  insecure: ["$NODE_IP:8080"]
  substitutions:
    "$SOURCE_IP:8080": "$NODE_IP:8080"
  credentialsFile: /etc/tobby/creds.json
retriever:
  source: /etc/tobby/retriever.yaml
trust:
  roots:
    - name: crucible
      key: |
$PUB_KEY_INDENTED
EOF
cat > "$WORK/down-retriever.yaml" <<EOF
apiVersion: recipe.tobby.dev/v1alpha1
kind: Retriever
metadata:
  name: crucible-zone-2
spec:
  cookbook: $NODE_IP:8080/${SOURCE_IP}_8080/cookbook
  recipes:
    - name: sample-app
      version: "2.x"
EOF
AUTH_B64=$(printf '%s' "$CRED" | base64 | tr -d '\n')
printf '{"auths":{"%s":{"auth":"%s"}}}\n' "$NODE_IP:8080" "$AUTH_B64" > "$WORK/creds.json"
inc exec tbc-m3-downstream -- mkdir -p /etc/tobby
inc file push "$WORK/down.yaml" tbc-m3-downstream/etc/tobby/config.yaml
inc file push "$WORK/down-retriever.yaml" tbc-m3-downstream/etc/tobby/retriever.yaml
inc file push "$WORK/creds.json" tbc-m3-downstream/etc/tobby/creds.json
inc exec tbc-m3-downstream -- sh -c "printf '%s\n' '$CRED_PASS' |
    tobby user add $CRED_USER --state-root /srv/state --password-stdin" >/dev/null
inc exec tbc-m3-downstream -- sh -c '
    nohup tobby serve --config /etc/tobby/config.yaml >>/var/log/tobby.log 2>&1 &
'
wait_ready tbc-m3-downstream http://127.0.0.1:8080/readyz

DAPI="http://$DOWN_IP:8080/api/v1"
DTASK=$(sync_and_wait "$DAPI" "$CRED") || fail "downstream synchronization never settled"
DSTATUS=$(curl -fsS -u "$CRED" "$DAPI/tasks/$DTASK" | jq -r '.task.status')
[ "$DSTATUS" = "done" ] || fail "downstream synchronization ended $DSTATUS"
DSTORED=$(curl -fsS -u "$CRED" "$DAPI/content/$RELOCATED/-/tags/2.0.0" | jq -r '.digest')
[ "$DSTORED" = "$IMG_DIGEST" ] ||
    fail "cascade digest $DSTORED differs from pinned $IMG_DIGEST"
DEFFECTIVE=$(curl -fsS -u "$CRED" "$DAPI/tasks/$DTASK" |
    jq -r '[.task.resolutions[] | select(.ingredient == "sample") | .effective] | first')
printf '%s' "$DEFFECTIVE" | grep -q "$NODE_IP:8080" ||
    fail "substitution not reported (effective: $DEFFECTIVE)"
check "cascade: unmodified recipe consumed through substitution, identical relocated path, digest intact"

# -- Cleanup ------------------------------------------------------------------
for inst in tbc-m3-source tbc-m3-node tbc-m3-downstream; do
    inc delete --force "$inst"
done
check "scenario m3 complete — report: $REPORT"
