#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Copyright © 2026 infraBuilder SASU and contributors
#
# Milestone-3 hermetic topology scenario (ADR-0014 tier 1,
# DEVELOPMENT-PLAN §2.3): the signed recipe engine, end to end through the
# real surfaces — Retriever, REAL cosign verification, cascade.
#
#   1. Fixtures: the source registry hosts a multi-arch image and a
#      cookbook holding a cooked recipe signed with a key generated by
#      this scenario (cosign key-based, ADR-0007, classic attached-tag
#      layout — RECIPE-SPEC §12.2).
#   2. A secure node synchronizes its Retriever: signature verified,
#      ingredients fetched by pinned digest under their relocated paths
#      (FR-035), platform selection sparse (FR-022), recipe + signature
#      copied into the local store.
#   3. Tampering: a recipe version signed by a FOREIGN key is refused
#      with TBY-SIG-001, per item — and nothing lands in the store.
#   4. Idempotence (NFR-009): a second synchronization moves zero bytes.
#   5. Cascade (FR-036): a downstream node with NO route to the source
#      registry consumes the first node's store through source
#      substitution, recipe UNMODIFIED — same relocated path, same pinned
#      digest. The canary proves the missing route before the cascade
#      relies on it.
#
# What this tier proves and what it does not. The signatures are produced
# and verified by the real cosign against a real registry, so the FR-033
# key-based path is exercised for real on every CI run; the Sigstore
# bundle layout (cosign 3.x default), the FileSet serving half of the
# milestone (FR-047), and real multi-node hardware stay the job of the
# crucible tier, which owns them (crucible/scenarios/m3).
#
# Requires: docker (compose v2), go, jq, and cosign — taken from the
# environment when present (the CI runner image ships it), installed at
# the crucible's pinned version otherwise. Run from the repository root:
#   sh test/topology/scenario-m3.sh
set -eu

TOPO_DIR="$(dirname "$0")"
COMPOSE="docker compose -f $TOPO_DIR/compose-m3.yaml"
GEN="$TOPO_DIR/.m3"
REPORT="${TOPOLOGY_REPORT:-/tmp/tobby-topology-m3-report.txt}"

SOURCE_PORT=5310
NODE_PORT=5311
DOWN_PORT=5312

CRED="admin:m3-scenario-pass"
API="http://127.0.0.1:$NODE_PORT/api/v1"
DAPI="http://127.0.0.1:$DOWN_PORT/api/v1"
# The relocated repository paths are computed by the convention (FR-035),
# never written by hand in a configuration: the scenario writes them down
# once, here, precisely so that a change to the convention breaks a check
# instead of quietly passing.
RELOCATED="source-registry_5000/library/sample"
COOKBOOK_REPO="source-registry_5000/cookbook/sample-app"

: >"$REPORT"
step() { printf '%s\n' "$*" | tee -a "$REPORT"; }
cleanup() {
    $COMPOSE down -v >/dev/null 2>&1 || true
    rm -rf "$GEN" "$TOPO_DIR/tobby"
}
fail() {
    step "FAIL $*"
    cleanup
    exit 1
}

for tool in docker go jq; do
    command -v "$tool" >/dev/null 2>&1 || fail "$tool is required by this scenario"
done

step "== milestone-3 topology scenario $(date -u +%Y-%m-%dT%H:%M:%SZ) =="

# -- Tooling: the real cosign signs the fixtures ------------------------------
# Same policy as the crucible m3 scenario: the environment's cosign when
# there is one, the pinned sumdb-verified build otherwise.
COSIGN="${COSIGN:-cosign}"
if ! command -v "$COSIGN" >/dev/null 2>&1; then
    GOBIN="$(pwd)/$GEN/bin" go install github.com/sigstore/cosign/v3/cmd/cosign@v3.0.4 ||
        fail "cosign unavailable and go install failed"
    COSIGN="$GEN/bin/cosign"
fi

# -- Build the binary under test and the topology image -----------------------
GOOS=linux CGO_ENABLED=0 go build -trimpath -o "$TOPO_DIR/tobby" ./cmd/tobby ||
    fail "building tobby"
docker build -q -t tobby-topology:local -f "$TOPO_DIR/Dockerfile.test" "$TOPO_DIR" >/dev/null ||
    fail "building the topology image"
rm -f "$TOPO_DIR/tobby"
step "ok   build: binary, topology image, cosign available ($($COSIGN version 2>/dev/null | grep GitVersion | awk '{print $2}' || echo unknown))"

$COMPOSE down -v >/dev/null 2>&1 || true
rm -rf "$GEN"
mkdir -p "$GEN"

# -- 1. Fixtures: image, key pairs, cooked signed recipes ---------------------
$COMPOSE up -d source-registry >/dev/null 2>&1 || $COMPOSE up -d source-registry ||
    fail "starting the source registry"
i=0
until curl -fsS "http://127.0.0.1:$SOURCE_PORT/v2/" >/dev/null 2>&1; do
    i=$((i + 1)); [ "$i" -gt 100 ] && fail "the source registry never came up"
    sleep 0.2
done

IMG_DIGEST=$(go run ./test/topology/seed push \
    "127.0.0.1:$SOURCE_PORT/library/sample:3.0.0") || fail "seeding the sample image"
(cd "$GEN" && COSIGN_PASSWORD= "$COSIGN" generate-key-pair >/dev/null 2>&1) ||
    fail "generating the trusted key pair"
(cd "$GEN" && COSIGN_PASSWORD= "$COSIGN" generate-key-pair --output-key-prefix foreign >/dev/null 2>&1) ||
    fail "generating the foreign key pair"

# The recipe names the ingredient by its IN-TOPOLOGY reference: the node
# resolves it from inside the compose network, while the driver seeds and
# signs through the host mapping — the digest is the same bytes either way.
# Two of the seeded index's three platforms are selected, so the sparse
# check below (FR-022) observes a choice, not a copy.
cat >"$GEN/sample-app.yaml" <<EOF
apiVersion: recipe.tobby.dev/v1alpha1
kind: Recipe
metadata:
  name: sample-app
  version: 3.0.0
spec:
  ingredients:
    - name: sample
      kind: ContainerImage
      ref: source-registry:5000/library/sample
      version: 3.0.0
      digest: $IMG_DIGEST
      platforms: [linux/amd64, linux/arm64]
EOF
RECIPE_DIGEST=$(go run ./test/topology/seed push-recipe \
    "127.0.0.1:$SOURCE_PORT/cookbook/sample-app:3.0.0" "$GEN/sample-app.yaml") ||
    fail "publishing the cooked recipe"

# cosign 3.x defaults to the new bundle format; RECIPE-SPEC §12.2 and
# ADR-0007 pin the classic attached-signature convention
# ("sha256-<hex>.sig") for these fixtures — --use-signing-config=false is
# what lets --tlog-upload=false through (no transparency log in a
# hermetic run).
sign_recipe() {
    COSIGN_PASSWORD= "$COSIGN" sign --key "$1" --yes --allow-insecure-registry \
        --use-signing-config=false --new-bundle-format=false --tlog-upload=false "$2"
}
sign_recipe "$GEN/cosign.key" "127.0.0.1:$SOURCE_PORT/cookbook/sample-app@$RECIPE_DIGEST" \
    >/dev/null 2>&1 || fail "cosign signing the recipe"

# A second version signed by a FOREIGN key: the tamper case. Only
# metadata.version is rewritten (two-space indent); the ingredient's
# version (six-space indent) must keep pointing at the tag the source
# registry actually carries.
sed 's/^  version: 3.0.0/  version: 3.0.1/' "$GEN/sample-app.yaml" >"$GEN/sample-app-3.0.1.yaml"
BAD_DIGEST=$(go run ./test/topology/seed push-recipe \
    "127.0.0.1:$SOURCE_PORT/cookbook/sample-app:3.0.1" "$GEN/sample-app-3.0.1.yaml") ||
    fail "publishing the foreign-signed recipe"
sign_recipe "$GEN/foreign.key" "127.0.0.1:$SOURCE_PORT/cookbook/sample-app@$BAD_DIGEST" \
    >/dev/null 2>&1 || fail "cosign signing with the foreign key"
step "ok   fixtures: image $IMG_DIGEST, recipe signed (trusted 3.0.0, foreign-signed 3.0.1)"

# -- 2. The two node configurations and their retrievers ----------------------
# The inline trust root is a YAML block scalar: its content must be
# indented MORE than the "key:" that introduces it (6 spaces), hence 8.
PUB_KEY_INDENTED=$(sed 's/^/        /' "$GEN/cosign.pub")
cat >"$GEN/node-config.yaml" <<EOF
mode: mirror
storage:
  root: /var/lib/tobby/store
state:
  root: /var/lib/tobby/state
server:
  addr: :8080
logging:
  level: debug
registries:
  insecure:
    - source-registry:5000
retriever:
  source: /etc/tobby/node-retriever.yaml
trust:
  roots:
    - name: topology-m3
      key: |
$PUB_KEY_INDENTED
EOF
cat >"$GEN/node-retriever.yaml" <<'EOF'
apiVersion: recipe.tobby.dev/v1alpha1
kind: Retriever
metadata:
  name: topology-zone-a
spec:
  cookbook: source-registry:5000/cookbook
  recipes:
    - name: sample-app
      version: "3.0.0"
EOF

# The downstream node consumes the FIRST node's store: its retriever
# names the relocated cookbook, its registries substitute the source host
# (FR-036) — the recipe document itself is untouched and still verifies
# against the same trust root — and its credentials file answers the
# upstream node's Basic challenge.
AUTH_B64=$(printf '%s' "$CRED" | base64 | tr -d '\n')
printf '{"auths":{"%s":{"auth":"%s"}}}\n' "tobby-node:8080" "$AUTH_B64" >"$GEN/creds.json"
cat >"$GEN/down-config.yaml" <<EOF
mode: mirror
storage:
  root: /var/lib/tobby/store
state:
  root: /var/lib/tobby/state
server:
  addr: :8080
logging:
  level: debug
registries:
  insecure:
    - tobby-node:8080
  substitutions:
    "source-registry:5000": "tobby-node:8080"
  credentialsFile: /etc/tobby/creds.json
retriever:
  source: /etc/tobby/down-retriever.yaml
trust:
  roots:
    - name: topology-m3
      key: |
$PUB_KEY_INDENTED
EOF
cat >"$GEN/down-retriever.yaml" <<'EOF'
apiVersion: recipe.tobby.dev/v1alpha1
kind: Retriever
metadata:
  name: topology-zone-b
spec:
  cookbook: tobby-node:8080/source-registry_5000/cookbook
  recipes:
    - name: sample-app
      version: "3.0.0"
EOF
step "ok   node configurations, retrievers, and downstream credentials generated"

# -- 3. Secure node: account, ready, first synchronization --------------------
printf '%s\n' "${CRED#*:}" | $COMPOSE run --rm -T tobby-node \
    user add "${CRED%%:*}" --state-root /var/lib/tobby/state --password-stdin \
    >/dev/null 2>&1 || fail "creating the node account"
$COMPOSE up -d tobby-node >/dev/null 2>&1 || $COMPOSE up -d tobby-node
i=0
until curl -fsS "http://127.0.0.1:$NODE_PORT/readyz" >/dev/null 2>&1; do
    i=$((i + 1)); [ "$i" -gt 100 ] && fail "the node never became ready"
    sleep 0.2
done
step "ok   secure node ready (trust root, retriever)"

sync_and_wait() {
    _api="$1"
    _tid=$(curl -fsS -u "$CRED" -X POST "$_api/sync" | jq -r '.task.id') || return 1
    _i=0
    while :; do
        _status=$(curl -fsS -u "$CRED" "$_api/tasks/$_tid" | jq -r '.task.status')
        case "$_status" in
        done | failed) break ;;
        esac
        _i=$((_i + 1))
        [ "$_i" -gt 300 ] && return 1
        sleep 0.4
    done
    printf '%s' "$_tid"
}

TASK1=$(sync_and_wait "$API") || fail "the first synchronization never settled"
STATUS=$(curl -fsS -u "$CRED" "$API/tasks/$TASK1" | jq -r '.task.status')
[ "$STATUS" = "done" ] || fail "the first synchronization ended $STATUS, want done"

STORED=$(curl -fsS -u "$CRED" "$API/content/$RELOCATED/-/tags/3.0.0" | jq -r '.digest')
[ "$STORED" = "$IMG_DIGEST" ] || fail "stored digest $STORED differs from pinned $IMG_DIGEST"
PRESENT=$(curl -fsS -u "$CRED" "$API/content/$RELOCATED/-/tags/3.0.0" |
    jq '[.platforms[] | select(.present)] | length')
[ "$PRESENT" = "2" ] || fail "present platforms $PRESENT, want the 2 selected (sparse index, FR-022)"
SIG_TAG="$(printf '%s' "$RECIPE_DIGEST" | sed 's/sha256:/sha256-/').sig"
curl -fsS -u "$CRED" "$API/content/$COOKBOOK_REPO/-/tags/3.0.0" >/dev/null ||
    fail "the recipe artifact is missing from the local cookbook path"
curl -fsS -u "$CRED" "$API/content/$COOKBOOK_REPO/-/tags/$SIG_TAG" >/dev/null ||
    fail "the recipe signature artifact was not copied (RECIPE-SPEC §12.2)"
step "ok   signed recipe synchronized: pinned digest intact, sparse index (2/3), signature copied"

# -- 4. Tampering: the foreign-signed recipe is refused per item --------------
# The retriever is rewritten IN PLACE (same inode) through the mounted
# /etc/tobby directory, then restored: the source is re-read on every
# cycle, no restart involved.
sed 's/version: "3.0.0"/version: "3.0.1"/' "$GEN/node-retriever.yaml" >"$GEN/node-retriever.tmp"
cat "$GEN/node-retriever.tmp" >"$GEN/node-retriever.yaml"
BAD_TASK=$(sync_and_wait "$API") || fail "the tamper synchronization never settled"
BAD_CODE=$(curl -fsS -u "$CRED" "$API/tasks/$BAD_TASK" |
    jq -r '[.task.items[] | select(.error != null) | .error.code] | first')
[ "$BAD_CODE" = "TBY-SIG-001" ] || fail "the foreign-signed recipe yielded $BAD_CODE, want TBY-SIG-001"
if curl -fsS -u "$CRED" "$API/content/$COOKBOOK_REPO/-/tags/3.0.1" >/dev/null 2>&1; then
    fail "the foreign-signed recipe landed in the store"
fi
sed 's/version: "3.0.1"/version: "3.0.0"/' "$GEN/node-retriever.tmp" >"$GEN/node-retriever.restore"
cat "$GEN/node-retriever.restore" >"$GEN/node-retriever.yaml"
rm -f "$GEN/node-retriever.tmp" "$GEN/node-retriever.restore"
step "ok   foreign-signed recipe refused (TBY-SIG-001), nothing landed"

# -- 5. Idempotence: the second synchronization moves zero bytes --------------
TASK2=$(sync_and_wait "$API") || fail "the second synchronization never settled"
MOVED=$(curl -fsS -u "$CRED" "$API/tasks/$TASK2" |
    jq '[.task.items[].size_bytes // 0] | add // 0')
[ "$MOVED" = "0" ] || fail "the second synchronization moved $MOVED bytes, want 0 (NFR-009)"
step "ok   idempotence: second synchronization moved zero bytes"

# -- 6. Cascade: downstream node, recipe unmodified, identical paths ----------
# The missing route is proven before the cascade relies on it: from the
# downstream segment, the source registry does not exist.
if $COMPOSE run --rm canary "curl -m 5 -fsS http://source-registry:5000/v2/" >/dev/null 2>&1; then
    fail "the downstream segment reached the source registry directly"
fi
step "ok   downstream segment has no route to the source registry (cascade is structural)"

printf '%s\n' "${CRED#*:}" | $COMPOSE run --rm -T tobby-downstream \
    user add "${CRED%%:*}" --state-root /var/lib/tobby/state --password-stdin \
    >/dev/null 2>&1 || fail "creating the downstream account"
$COMPOSE up -d tobby-downstream >/dev/null 2>&1 || $COMPOSE up -d tobby-downstream
i=0
until curl -fsS "http://127.0.0.1:$DOWN_PORT/readyz" >/dev/null 2>&1; do
    i=$((i + 1)); [ "$i" -gt 100 ] && fail "the downstream node never became ready"
    sleep 0.2
done

DTASK=$(sync_and_wait "$DAPI") || fail "the downstream synchronization never settled"
DJSON=$(curl -fsS -u "$CRED" "$DAPI/tasks/$DTASK")
DSTATUS=$(printf '%s' "$DJSON" | jq -r '.task.status')
[ "$DSTATUS" = "done" ] || fail "the downstream synchronization ended $DSTATUS: $(printf '%s' "$DJSON" | jq -c '[.task.items[] | select(.status == "failed") | {name, error}]')"
DSTORED=$(curl -fsS -u "$CRED" "$DAPI/content/$RELOCATED/-/tags/3.0.0" | jq -r '.digest')
[ "$DSTORED" = "$IMG_DIGEST" ] ||
    fail "the cascade digest $DSTORED differs from the pinned $IMG_DIGEST"
DEFFECTIVE=$(printf '%s' "$DJSON" |
    jq -r '[.task.resolutions[] | select(.ingredient == "sample") | .effective] | first')
printf '%s' "$DEFFECTIVE" | grep -q "tobby-node:8080" ||
    fail "the substitution was not reported (effective: $DEFFECTIVE)"
step "ok   cascade: unmodified recipe consumed through substitution, identical relocated path, digest intact"

cleanup
step "== scenario m3 PASSED — raw report: $REPORT =="
