import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightLinksValidator from "starlight-links-validator";

// GitHub Pages project site for the tobby-fetch/tobby-fetch repository.
// Served at https://tobby-fetch.github.io/tobby-fetch/
// If a custom domain is assigned later, set `site` to it and remove `base`.
//
// The documentation lives under /docs/ (Starlight, English canonical,
// French under /fr/docs/). The marketing pages (src/pages/) keep their
// own layout and identity; the whole build stays static so the binary
// can embed it (go:embed, no Node at runtime).
export default defineConfig({
  site: "https://tobby-fetch.github.io",
  base: "/tobby-fetch",
  integrations: [
    starlight({
      title: "Tobby",
      description:
        "Documentation for Tobby — fetch OCI assets across every zone, all the way to air-gap.",
      defaultLocale: "root",
      locales: {
        root: { label: "English", lang: "en" },
        fr: { label: "Français", lang: "fr" },
      },
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/tobby-fetch/tobby-fetch",
        },
      ],
      customCss: ["./src/styles/starlight.css"],
      plugins: [
        // Fails the build on any broken internal link or anchor — with
        // dozens of cross-referencing pages this is a quality gate, not
        // a convenience.
        starlightLinksValidator({
          errorOnFallbackPages: false,
          // Pages link each other relatively so the tree keeps working
          // when embedded in the binary under a different base.
          errorOnRelativeLinks: false,
        }),
      ],
      // Sections are autogenerated from the directory tree; each page
      // carries its own order and status badge in frontmatter
      // (sidebar.order / sidebar.badge) — see website/README-docs.md.
      sidebar: [
        {
          label: "Discover",
          translations: { fr: "Découvrir" },
          items: [{ autogenerate: { directory: "docs/discover" } }],
        },
        {
          label: "Try it in 10 minutes",
          translations: { fr: "Essayer en 10 minutes" },
          items: [{ autogenerate: { directory: "docs/try" } }],
        },
        {
          label: "Connected zones (passthrough)",
          translations: { fr: "Zones connectées (passthrough)" },
          items: [{ autogenerate: { directory: "docs/passthrough" } }],
        },
        {
          label: "Isolated zones (air-gap)",
          translations: { fr: "Zones isolées (air-gap)" },
          items: [{ autogenerate: { directory: "docs/air-gap" } }],
        },
        {
          label: "Writing recipes",
          translations: { fr: "Écrire des recipes" },
          items: [{ autogenerate: { directory: "docs/recipes" } }],
        },
        {
          label: "Security",
          translations: { fr: "Sécurité" },
          items: [{ autogenerate: { directory: "docs/security" } }],
        },
        {
          label: "Auditing the project",
          translations: { fr: "Auditer le projet" },
          items: [{ autogenerate: { directory: "docs/project" } }],
        },
        {
          label: "Reference",
          translations: { fr: "Référence" },
          items: [{ autogenerate: { directory: "docs/reference" } }],
        },
      ],
    }),
  ],
});
